openapi: 3.0.0
info:
  title: Azure Policy Governance API v2
  description: API for querying Azure Policy definitions, assignments, compliance states, and triggering remediation. Optimized for use as an agent tool.
  version: "2.0"
servers:
  - url: https://management.azure.com
paths:
  /subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyDefinitions:
    get:
      operationId: ListPolicyDefinitions
      summary: List all policy definitions in a subscription
      description: Retrieves all policy definitions in the subscription including display name, description, policy type, mode, category, version, and policy rule (condition and effect).
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: "2023-04-01"
        - name: $filter
          in: query
          required: false
          schema:
            type: string
          description: OData filter expression to filter policy definitions.
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        properties:
                          type: object
                          properties:
                            displayName:
                              type: string
                            description:
                              type: string
                            policyType:
                              type: string
                            mode:
                              type: string
                            metadata:
                              type: object
                              properties:
                                category:
                                  type: string
                                version:
                                  type: string
                            policyRule:
                              type: object
                              properties:
                                if:
                                  type: object
                                then:
                                  type: object
                                  properties:
                                    effect:
                                      type: string

  /subscriptions/{subscriptionId}/providers/Microsoft.Authorization/policyAssignments:
    get:
      operationId: ListPolicyAssignments
      summary: List all policy assignments in a subscription
      description: Retrieves all active policy assignments in the subscription.
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: "2023-04-01"
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                        name:
                          type: string
                        properties:
                          type: object
                          properties:
                            displayName:
                              type: string
                            scope:
                              type: string
                            policyDefinitionId:
                              type: string
                            parameters:
                              type: object

  /subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/queryResults:
    post:
      operationId: QueryPolicyComplianceStates
      summary: Query policy compliance states
      description: Queries the latest policy compliance states for resources in the subscription.
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            enum: ["2019-10-01"]
            default: "2019-10-01"
        - name: $filter
          in: query
          required: false
          schema:
            type: string
          description: "OData filter expression. Field names must use PascalCase (e.g., ComplianceState eq 'NonCompliant', not complianceState)."
        - name: $apply
          in: query
          required: false
          schema:
            type: string
          description: OData apply expression for aggregations.
        - name: $top
          in: query
          required: false
          schema:
            type: integer
          description: Maximum number of records to return.
        - name: $orderby
          in: query
          required: false
          schema:
            type: string
          description: OData orderby expression.
        - name: $select
          in: query
          required: false
          schema:
            type: string
          description: Select specific fields to return.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  "@odata.nextLink":
                    type: string
                  "@odata.context":
                    type: string
                  "@odata.count":
                    type: integer
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        timestamp:
                          type: string
                          format: date-time
                        resourceId:
                          type: string
                        policyAssignmentId:
                          type: string
                        policyAssignmentName:
                          type: string
                        policyAssignmentScope:
                          type: string
                        policyDefinitionId:
                          type: string
                        policyDefinitionName:
                          type: string
                        policyDefinitionAction:
                          type: string
                        policyDefinitionCategory:
                          type: string
                        policySetDefinitionId:
                          type: string
                        policySetDefinitionName:
                          type: string
                        policySetDefinitionCategory:
                          type: string
                        complianceState:
                          type: string
                          enum: [Compliant, NonCompliant, Unknown, Conflict, Exempt]
                        subscriptionId:
                          type: string
                        resourceType:
                          type: string
                        resourceLocation:
                          type: string
                        resourceGroup:
                          type: string
                        resourceTags:
                          type: string
                        policyAssignmentParameters:
                          type: string
                        complianceReasonCode:
                          type: string
                        managementGroupIds:
                          type: string

  /subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/summarize:
    post:
      operationId: SummarizeCompliance
      summary: Summarize policy compliance data
      description: Retrieves aggregated compliance summary counts per policy assignment and definition.
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            enum: ["2019-10-01"]
            default: "2019-10-01"
        - name: $top
          in: query
          required: false
          schema:
            type: integer
          description: Maximum number of policy assignment summaries to return.
        - name: $filter
          in: query
          required: false
          schema:
            type: string
          description: OData filter expression.
      requestBody:
        required: false
        content:
          application/json:
            schema:
              type: object
      responses:
        "200":
          description: Success.
          content:
            application/json:
              schema:
                type: object
                properties:
                  value:
                    type: array
                    items:
                      type: object
                      properties:
                        results:
                          type: object
                          properties:
                            nonCompliantResources:
                              type: integer
                            nonCompliantPolicies:
                              type: integer
                        policyAssignments:
                          type: array
                          items:
                            type: object
                            properties:
                              policyAssignmentId:
                                type: string
                              policySetDefinitionId:
                                type: string
                              results:
                                type: object
                                properties:
                                  nonCompliantResources:
                                    type: integer
                                  nonCompliantPolicies:
                                    type: integer
                              policyDefinitions:
                                type: array
                                items:
                                  type: object
                                  properties:
                                    policyDefinitionId:
                                      type: string
                                    policyDefinitionReferenceId:
                                      type: string
                                    effect:
                                      type: string
                                    results:
                                      type: object
                                      properties:
                                        nonCompliantResources:
                                          type: integer

  /subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/remediations/{remediationName}:
    put:
      operationId: TriggerRemediation
      summary: Trigger a remediation task
      description: Creates or updates a remediation task to fix non-compliant resources for a policy assignment.
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: remediationName
          in: path
          required: true
          schema:
            type: string
          description: The name of the remediation task to create or update.
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: "2021-10-01"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                properties:
                  type: object
                  required:
                    - policyAssignmentId
                  properties:
                    policyAssignmentId:
                      type: string
                      description: The resource ID of the policy assignment to remediate.
                    policyDefinitionReferenceId:
                      type: string
                      description: The policy definition reference ID within an initiative for initiative-specific remediation.
                    resourceDiscoveryMode:
                      type: string
                      description: "How resources to remediate are discovered. ExistingNonCompliant or ReEvaluateCompliance."
                    filters:
                      type: object
                      properties:
                        locations:
                          type: array
                          items:
                            type: string
                          description: List of Azure regions to restrict remediation to.
      responses:
        "200":
          description: Task updated.
        "201":
          description: Task created.

  /subscriptions/{subscriptionId}/providers/Microsoft.PolicyInsights/policyStates/latest/triggerEvaluation:
    post:
      operationId: TriggerPolicyScan
      summary: Trigger an on-demand policy compliance scan
      description: Initiates an on-demand policy compliance evaluation for all resources in the subscription.
      parameters:
        - name: subscriptionId
          in: path
          required: true
          schema:
            type: string
          description: "The Azure Subscription ID provided by the user. This is a GUID such as 4bfd1047-ae46-4bd4-9175-78a1ee7b62b5. Extract this value from the user's query."
        - name: api-version
          in: query
          required: true
          schema:
            type: string
            default: "2019-10-01"
      responses:
        "202":
          description: Accepted. The scan has been triggered.
          headers:
            Location:
              schema:
                type: string
              description: URL to poll for scan completion status.
